### ISSUE TITLE
Error on replay with wrong app hash calculation (block #914381)

### ISSUE THREAD

**Issue by cyborgshead** [cyberia-to/go-cyber#197]
### Current Behavior
[comment]: # (Describe what actually happened.)
Cyberd validator node stack on block 914381 with error on replay and wrong app hash

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Continuing of sync and get online validation

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Ubuntu 18.04.01 LTS/NVIDIA-SMI 415.27/Driver Version: 415.27/CUDA Version: 10.0
i7-7700K @ 4.20GHz/  32GB RAM / MSI GTX 1070 8GB / 512 SSD

### Log
[comment]: # (Also you can attach log to this issue.)

```
panic: Panicked questionably: Failed to process committed block (914381:9F818FD2149C6CC6E52AF7A4932734D09732BDDEAB629D699B8888BDC0CD1C4E): Wrong Block.Header.AppHash.  Expected 64D2D5DF2A679423AACB803DFAF79D8BA3BB224919BD5FC034A491C9075E8283, got 292590BC3F2700FBF3C47178DD37638118A92E720AE03C5FA0D546D1C7B29388

goroutine 529363 [running]:
github.com/tendermint/tendermint/libs/common.PanicQ(0xe2bc20, 0xc00d5b8520)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.27.4/libs/common/errors.go:245 +0xb8
github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc0000f6680)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.27.4/blockchain/reactor.go:341 +0x1033
created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.27.4/blockchain/reactor.go:118 +0x89
ERROR: Error during handshake: Error on replay: Wrong Block.Header.AppHash.  Expected 64D2D5DF2A679423AACB803DFAF79D8BA3BB224919BD5FC034A491C9075E8283, got 292590BC3F2700FBF3C47178DD37638118A92E720AE03C5FA0D546D1C7B29388
ERROR: Error during handshake: Error on replay: Wrong Block.Header.AppHash.  Expected 64D2D5DF2A679423AACB803DFAF79D8BA3BB224919BD5FC034A491C9075E8283, got 292590BC3F2700FBF3C47178DD37638118A92E720AE03C5FA0D546D1C7B29388
ERROR: Error during handshake: Error on replay: Wrong Block.Header.AppHash.  Expected 64D2D5DF2A679423AACB803DFAF79D8BA3BB224919BD5FC034A491C9075E8283, got 292590BC3F2700FBF3C47178DD37638118A92E720AE03C5FA0D5
```

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by hleb-albau** [comment]
@litvintech yeah, reproduced. Currently, we don't know exactly bug, need more investigation. 
But, already knowing that this happens on soft fork block. Seems, some hidden bug on index loading after reload.

**Comment by hleb-albau** [comment]
@litvintech @xhipster @arturalbov Bad news, there is a bug, that causes all full nodes joining network right now to panic at 914381. Bug related, to our wrong assumption of stake update in cosmos-sdk. We miss user stake update for jailing validators and calculate the wrong rank using wrong user stake. There is no easy way to eliminate it for current testnet. So, I suggest focussing on fixing the bug and moving to #205. 
There is no easy way to track bounded stake in cosmos right now, so maybe for 0.1.1 we should change the rank calculation to honor only **NotBounded** user stake, and investigate ways to archive **bounded +unboded stake** for next testnets.
